### ISSUE TITLE
Clarify Usage in NixOS configuration

### ISSUE THREAD

**Issue by MartinLoeper** [brumhard/krewfile#10]
I tried to use this home-manager in a nixos configration and could not make it work.
Did you guys use this in a [standalone hm installation](https://nix-community.github.io/home-manager/index.xhtml#sec-install-standalone) only or also in a [nixos module](https://nix-community.github.io/home-manager/index.xhtml#sec-install-nixos-module)?

I get a recursion error when using it in my nixos config like:
```
error: infinite recursion encountered
       at /nix/store/nr5nl3zwzl02x3rnikjbry3s5xy7bm1d-source/lib/modules.nix:245:34:
          244|           (regularModules ++ [ internalModule ])
          245|           ({ inherit lib options config specialArgs; } // specialArgs);
             |                                  ^
          246|         in mergeModules prefix (reverseList collected);
```

**Comment by brumhard** [comment]
Hi there, I'm using home-manager on top of nix-darwin, so not sure how you would use it in nixos unfortunately.

For my darwin flake it looks like this:

```nix
darwinConfigurations.somehost = darwin.lib.darwinSystem {
  modules = [
    # ...
    home-manager.darwinModules.home-manager
    {
      nixpkgs = nixpkgsConfig;
      home-manager = {
        extraSpecialArgs = {
          inherit inputs;
        };
        users.someuser = {pkgs, ...}: {
          imports = [./home];
        };
        # ...
      };
    }
  ];
};  
```

And then in the `./home` I configure krew as described in the README.

Not sure if @rgroemmer has a nixos config maybe?

**Comment by MartinLoeper** [comment]
Thanks for the advice @brumhard 
Using your example I got it working as follows in my nixos config:

- add the krewfile input to flake.nix:   
```nix
inputs = {
  krewfile = {
    url = "github:brumhard/krewfile";
    inputs.nixpkgs.follows = "nixpkgs";
  };
  home-manager = {
    url = "github:nix-community/home-manager?ref=master";
    inputs.nixpkgs.follows = "nixpkgs";
  };
}
```
- propagate the krewfile hm module s.t. krewfile can be access in the file which configures home-manager below:
```nix
nixpkgs.lib.nixosSystem {
  specialArgs =  {
    inherit krewfile;
  };
  modules = [
    home-manager.nixosModules.default
    ./home.nix
  ];
}
```
- add the following import to the hm config in home.nix - not the top-level nixos config - which was my primary fault!   
As someone who is not using standalone home-manager (on darwin or linux) I was not aware that hm has a dedicated `imports` attribute.
```nix
{ pkgs, krewfile, ... }: 
{
  home-manager.users.mloeper = {
    imports = [
      krewfile.homeManagerModules.krewfile
    ];

    programs = {
      krewfile = {
        enable = true;
        krewPackage = pkgs.krew;
        plugins = [
          "directpv"
          "oidc-login"
          "pv-migrate"
        ];
      };
    };
}
```

**Comment by RAPSNX** [comment]
@MartinLoeper 

Yes, you can also call the `home-manager.nixosModules` directly.
And there is a dedicated attribute for `home-manager` called `extraSpecialArgs` if you want to separate it from the `flake.nix`.

```nix
nixpkgs.lib.nixosSystem {
  specialArgs =  {
    # nixos special args
  };
  modules = [
      # nixos modules import or call
          home-manager.nixosModule
          {
            home-manager = {
              extraSpecialArgs = { krewfile };
              users.${user} = import ./home.nix
            };
          }
  ];
```
I think `imports` is a built-in `nix` attribute and not only dedicated to the `home-manager` module.
It will include any nix-expression to the actual configuration.

The `home-manager.users.mloeper` expects a nix-expression, so you can also include it inline:

```nix
home-manager.users.mloeper = { ... }: {
  imports [];
};
```

**Comment by MartinLoeper** [comment]
Thanks for the detailed explanation @rgroemmer!
Regarding the `imports` statement: There was a confusing issue when I placed the following statement into the top-level nixosSystem config instead of `home-manager.users.mloeper` (as in your example above):

```nix
imports = [
  krewfile.homeManagerModules.krewfile
];
```

I guess a home-manager module has to be imported below the `home-manager` attribute?

**Comment by RAPSNX** [comment]
> Thanks for the detailed explanation @rgroemmer! Regarding the `imports` statement: There was a confusing issue when I placed the following statement into the top-level nixosSystem config instead of `home-manager.users.mloeper` (as in your example above):
> 
> ```nix
> imports = [
>   krewfile.homeManagerModules.krewfile
> ];
> ```
> 
> I guess a home-manager module has to be imported below the `home-manager` attribute?

Correct, if you import it top level, then the `attrs` of the `krewfile` hm-module will be in the scope of your `nixpkgs.lib.nixosSystem` configuration.
This will break because the module uses `home-manager` specific attributes like ` home.activation`.

Not sure why you got "infinite recursion", this seems to be a config problem.
