### ISSUE TITLE
NixOS / Home-manager module

### ISSUE THREAD

**Issue by stv0g** [brumhard/krewfile#3]
I think it would be pretty neat if the flake could also provide a NixOS module for declaring krew plugins in your NixOS config

**Comment by brumhard** [comment]
Hi there, 
I'm not too familiar with writing a homemanager/nixos module but I usually do the following, after adding krewfile to the pkgs overlay for the homemanager:

```nix
{
  pkgs,
  lib,
  ...
}: let
  krewfile = pkgs.writeText "krewfile" ''
    modify-secret
    neat
    oidc-login
    pv-migrate
    stern
    explore
    get-all
    node-shell
    krew
  '';
in {
  home.activation.krew = lib.hm.dag.entryAfter ["writeBoundary"] ''
    $DRY_RUN_CMD ${pkgs.krewfile}/bin/krewfile -command ${pkgs.krew}/bin/krew -file ${krewfile}
  '';
}
```

 Does that fit you?

**Comment by stv0g** [comment]
Yes thats a good starting point for a module :)

**Comment by RAPSNX** [comment]
Also thought this would be neat to configure it directly `home-manager` via module.
Therefore, started to add a basic module: #5

**Comment by brumhard** [comment]
Released with https://github.com/brumhard/krewfile/releases/tag/v0.5.0
