### ISSUE TITLE
Comment support

### ISSUE THREAD

**Issue by MPV** [brumhard/krewfile#4]
Thanks for your efforts on this! ❤️ 

Wouldn't it be nice if the `krewfile` supported comments? 

For example I've run into a krew plugin not being available (yet) on arm / Apple Silicon platform, hence I'd like to leave a comment in my krewfile pointing for example to:
- https://github.com/kubernetes/ingress-nginx/issues/8194

**Comment by brumhard** [comment]
Hi there, this is now supported by using a `#`. Anything after the `#` will be ignored. It's now also included in the example in the README.
Feel free to reopen if you have further comments 🙂
